import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// Variable Inter — loads a single file covering weights 100–900.
// Cyrillic subset is included for Ukrainian text.
// font-display: swap is applied automatically by next/font.
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>{children}</body>
    </html>
  );
}
